version: "3.9"

services:
  postgres:
    image: postgres:16.0
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/schema-postgres.sql:/docker-entrypoint-initdb.d/create_tables.sql
    env_file:
      - .env
